version: '3.9'
services:
  ############################################## NGINX ##############################################
  nginx:
    image: nginx:1.21.6-alpine
    configs:
      - source: nginx-config
        target: /etc/nginx/nginx.conf
      - source: nginx-fleetdm-config
        target: /etc/nginx/conf.d/fleet.conf
    secrets:
      - fleetdm-tls-cert
      - fleetdm-tls-key
    ports: 
      - 8000:80
      - 8443:443
    networks: 
      - default
      - fleet-backend
    depends_on: 
      - fleet
    deploy:
      resources:
        limits:
          memory: 150M
        reservations:
          memory: 100M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 50
        window: 120s

  ############################################## fleet with config ##############################################
  fleet:
    image: fleetdm/fleet:v4.11.0
    command: sh -c "/usr/bin/fleet prepare db --config /etc/fleet/fleet.yml && /usr/bin/fleet serve --config /etc/fleet/fleet.yml"
    configs:
      - source: fleetdm-config
        target: /etc/fleet/fleet.yml
    secrets:
      - mysql-fleetdm-password
      - fleetdm-jwt-key
      - fleetdm-tls-cert
      - fleetdm-tls-key
    networks: 
      - fleet-backend
    depends_on:
      - mysql
      - redis
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 100M
        reservations:
          memory: 50M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 120s
  
  ############################################## fleet with ENV vars ##############################################
  # fleet:
  #   image: fleetdm/fleet:v4.11.0
  #   command: sh -c "/usr/bin/fleet prepare db && /usr/bin/fleet serve"
  #   environment:
  #     FLEET_MYSQL_ADDRESS: mysql:3306
  #     FLEET_MYSQL_DATABASE: fleet
  #     FLEET_MYSQL_USERNAME: fleet
  #     FLEET_MYSQL_PASSWORD_PATH: /run/secrets/mysql-fleetdm-password
  #     FLEET_REDIS_ADDRESS: redis:6379
  #     FLEET_SERVER_ADDRESS: 0.0.0.0:8080
  #     FLEET_AUTH_JWT_KEY_PATH: /run/secrets/fleetdm-jwt-key
  #     FLEET_SERVER_CERT: /run/secrets/fleetdm-tls-cert
  #     FLEET_SERVER_KEY: /run/secrets/fleetdm-tls-key
  #     FLEET_LOGGING_JSON: 'true'
  #     #FLEET_OSQUERY_STATUS_LOG_PLUGIN: filesystem
  #     #FLEET_FILESYSTEM_STATUS_LOG_FILE: /var/log/osquery/status.log
  #     #FLEET_OSQUERY_RESULT_LOG_PLUGIN: filesystem
  #     #FLEET_FILESYSTEM_RESULT_LOG_FILE: /var/log/osquery/result.log
  #   secrets:
  #     - mysql-fleetdm-password
  #     - fleetdm-jwt-key
  #     - fleetdm-tls-cert
  #     - fleetdm-tls-key
  #   networks: 
  #     - fleet-backend
  #   depends_on:
  #     - mysql
  #     - redis
  #   deploy:
  #     mode: replicated
  #     replicas: 1
  #     resources:
  #       limits:
  #         #cpus: '2'
  #         memory: 100M
  #       reservations:
  #         #cpus: '0.5'
  #         memory: 50M
  #     restart_policy:
  #       condition: on-failure
  #       delay: 5s
  #       max_attempts: 10
  #       window: 120s
  
  ############################################## MySQL ##############################################
  mysql:
    image: mysql:8.0.27
    configs:
      - source: mysql-fleetdm-config
        target: /etc/mysql/conf.d/fleetdm.cnf
    environment: 
      MYSQL_ROOT_PASSWORD_FILE: "/run/secrets/mysql-root-password"
      MYSQL_PASSWORD_FILE: "/run/secrets/mysql-fleetdm-password"
      MYSQL_DATABASE: "fleet"
      MYSQL_USER: "fleet"
    secrets:
      - mysql-root-password
      - mysql-fleetdm-password
    volumes: 
      - fleet-db:/var/lib/mysql
    networks: 
      - fleet-backend
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: '300M'
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s


  ############################################## Redis ##############################################
  redis:
    image: redis:6.2.6-alpine
    networks: 
      - fleet-backend
    deploy:
      resources:
        limits:
          memory: 100M
        reservations:
          memory: 50M
      restart_policy:
        condition: on-failure

volumes:
  fleet-db:
  fleet-logs:

networks:
  fleet-backend:

configs:
  nginx-config:
    file: ./conf/docker/nginx/nginx.conf
  nginx-fleetdm-config:
    file: ./conf/docker/nginx/fleetdm-swarm.conf
  mysql-fleetdm-config:
    file: ./conf/docker/mysql/fleetdm.cnf
  fleetdm-config:
    file: ./conf/docker/fleetdm/fleetdm-swarm.yml

secrets:
  mysql-root-password:
    external: true
  mysql-fleetdm-password:
    external: true
  fleetdm-tls-cert:
    file: conf/tls/fleet.crt
  fleetdm-tls-key:
    file: conf/tls/fleet.key
  fleetdm-jwt-key:
    external: true
