version: '3.9'
services:
  ############################################## fleet with config ##############################################
  fleet:
    image: fleetdm/fleet:v4.3.1
    command: sh -c "/usr/bin/fleet prepare db --config /etc/fleet/fleet.yml && /usr/bin/fleet serve --config /etc/fleet/fleet.yml"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fleet.rule=Host(`fleet.hackinglab.local`)"
      - "traefik.http.routers.fleet.tls=true"
      - "traefik.docker.network=traefik_traefik-net"
      - "traefik.http.services.fleet.loadbalancer.server.port=8080"
    configs:
      - source: fleetdm-config
        target: /etc/fleet/fleet.yml
    secrets:
      - mysql-fleetdm-password
      - fleetdm-jwt-key
      - fleetdm-tls-cert
      - fleetdm-tls-key
    networks: 
      - traefik_traefik-net
      - fleet-backend
    depends_on:
      - mysql
      - redis
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 100M
        reservations:
          memory: 50M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 120s
  
  ############################################## MySQL ##############################################
  mysql:
    image: mysql:8.0
    configs:
      - source: mysql-fleetdm-config
        target: /etc/mysql/conf.d/fleetdm.cnf
    environment: 
      MYSQL_ROOT_PASSWORD_FILE: "/run/secrets/mysql-root-password"
      MYSQL_PASSWORD_FILE: "/run/secrets/mysql-fleetdm-password"
      MYSQL_DATABASE: "fleet"
      MYSQL_USER: "fleet"
    secrets:
      - mysql-root-password
      - mysql-fleetdm-password
    volumes: 
      - fleet-db:/var/lib/mysql
    networks: 
      - fleet-backend
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: '300M'
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s


  ############################################## Redis ##############################################
  redis:
    image: redis:6.2.5-alpine
    networks: 
      - fleet-backend
    deploy:
      resources:
        limits:
          memory: 100M
        reservations:
          memory: 50M
      restart_policy:
        condition: on-failure

volumes:
  fleet-db:
  fleet-logs:

networks:
  fleet-backend:
  traefik_traefik-net:
    external: true

configs:
  mysql-fleetdm-config:
    file: ./conf/docker/mysql/fleetdm.cnf
  fleetdm-config:
    file: ./conf/docker/fleetdm/fleetdm-swarm-traefik.yml

secrets:
  mysql-root-password:
    external: true
  mysql-fleetdm-password:
    external: true
  fleetdm-tls-cert:
    file: conf/tls/fleet.crt
  fleetdm-tls-key:
    file: conf/tls/fleet.key
  fleetdm-jwt-key:
    external: true
