version: '3.7'
services:
  ############################################## NGINX ##############################################
  nginx:
    image: nginx:1.19.5-alpine
    configs:
      - source: nginx-config
        target: /etc/nginx/nginx.conf
      - source: nginx-fleetdm-config
        target: /etc/nginx/conf.d/fleet.conf
    secrets:
      - fleetdm-tls-cert
      - fleetdm-tls-key
    ports: 
      - 8000:80
      - 8443:443
    networks: 
      - default
      - fleet-backend
    depends_on: 
      - fleet
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 150M
        reservations:
          cpus: '0.25'
          memory: 100M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 50
        window: 120s


  ############################################## fleet with config ##############################################
  # fleet:
  #   image: fleetdm/fleet:3.6.0
  #   command: sh -c "/usr/bin/fleet prepare db --config /etc/fleet/fleet.yml && /usr/bin/fleet serve --config /etc/fleet/fleet.yml"
  #   configs:
  #     - source: fleetdm-config
  #       target: /etc/fleet/fleet.yml
  #   secrets:
  #     - mysql-fleetdm-password
  #     - fleetdm-jwt-key
  #     - fleetdm-tls-cert
  #     - fleetdm-tls-key
  #   volumes: 
  #     - fleet-logs:/var/log/osquery
  #   networks: 
  #     - fleet-backend
  #   depends_on:
  #     - mysql
  #     - redis
  #   deploy:
  #     mode: replicated
  #     replicas: 3
  #     resources:
  #       limits:
  #         cpus: '2'
  #         memory: 100M
  #       reservations:
  #         cpus: '0.5'
  #         memory: 50M
  #     restart_policy:
  #       condition: on-failure
  #       delay: 5s
  #       max_attempts: 10
  #       window: 120s
  
  ############################################## fleet with ENV vars ##############################################
  fleet:
    image: fleetdm/fleet:3.7.1
    command: sh -c "/usr/bin/fleet prepare db && /usr/bin/fleet serve"
    environment:
      KOLIDE_MYSQL_ADDRESS: mysql:3306
      KOLIDE_MYSQL_DATABASE: fleet
      KOLIDE_MYSQL_USERNAME: fleet
      KOLIDE_MYSQL_PASSWORD_PATH: /run/secrets/mysql-fleetdm-password
      KOLIDE_REDIS_ADDRESS: redis:6379
      KOLIDE_SERVER_ADDRESS: 0.0.0.0:8080
      KOLIDE_AUTH_JWT_KEY_PATH: /run/secrets/fleetdm-jwt-key
      KOLIDE_SERVER_CERT: /run/secrets/fleetdm-tls-cert
      KOLIDE_SERVER_KEY: /run/secrets/fleetdm-tls-key
      KOLIDE_LOGGING_JSON: 'true'
      #KOLIDE_OSQUERY_STATUS_LOG_PLUGIN: filesystem
      #KOLIDE_FILESYSTEM_STATUS_LOG_FILE: /var/log/osquery/status.log
      #KOLIDE_OSQUERY_RESULT_LOG_PLUGIN: filesystem
      #KOLIDE_FILESYSTEM_RESULT_LOG_FILE: /var/log/osquery/result.log
    secrets:
      - mysql-fleetdm-password
      - fleetdm-jwt-key
      - fleetdm-tls-cert
      - fleetdm-tls-key
    volumes: 
      - fleet-logs:/var/log/osquery
    networks: 
      - fleet-backend
    depends_on:
      - mysql
      - redis
    deploy:
      mode: replicated
      replicas: 3
      resources:
        limits:
          cpus: '2'
          memory: 100M
        reservations:
          cpus: '0.5'
          memory: 50M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 120s
  
  ############################################## MySQL ##############################################
  mysql:
    image: mysql:8.0
    configs:
      - source: mysql-fleetdm-config
        target: /etc/mysql/conf.d/fleetdm.cnf
    environment: 
      MYSQL_ROOT_PASSWORD_FILE: "/run/secrets/mysql-root-password"
      MYSQL_PASSWORD_FILE: "/run/secrets/mysql-fleetdm-password"
      MYSQL_DATABASE: "fleet"
      MYSQL_USER: "fleet"
    secrets:
      - mysql-root-password
      - mysql-fleetdm-password
    volumes: 
      - fleet-db:/var/lib/mysql
    networks: 
      - fleet-backend
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1G
        reservations:
          cpus: '1'
          memory: '300M'
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s


  ############################################## Redis ##############################################
  redis:
    image: redis:6.0.9-alpine
    networks: 
      - fleet-backend
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 100M
        reservations:
          cpus: '0.5'
          memory: 50M
      restart_policy:
        condition: on-failure

volumes:
  fleet-db:
  fleet-logs:

networks:
  fleet-backend:

configs:
  nginx-config:
    file: ./conf/docker/nginx/nginx.conf
  nginx-fleetdm-config:
    file: ./conf/docker/nginx/fleetdm-swarm.conf
  mysql-fleetdm-config:
    file: ./conf/docker/mysql/fleetdm.cnf
  fleetdm-config:
    file: ./conf/docker/fleetdm/fleetdm-swarm.yml

secrets:
  mysql-root-password:
    external: true
  mysql-fleetdm-password:
    external: true
  fleetdm-tls-cert:
    file: conf/tls/fleet.crt
  fleetdm-tls-key:
    file: conf/tls/fleet.key
  fleetdm-jwt-key:
    external: true
