version: '3.9'
services:
  ############################################## fleet with config ##############################################
  fleet:
    image: fleetdm/fleet:3.8.0
    command: sh -c "/usr/bin/fleet prepare db --config /etc/fleet/fleet.yml && /usr/bin/fleet serve --config /etc/fleet/fleet.yml"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fleet.rule=Host(`fleet.hackinglab.local`)"
      - "traefik.http.routers.fleet.tls=true"
      - "traefik.docker.network=traefik_traefik-net"
      - "traefik.http.services.fleet.loadbalancer.server.port=8080"
    configs:
      - source: fleetdm-config
        target: /etc/fleet/fleet.yml
    secrets:
      - mysql-fleetdm-password
      - fleetdm-jwt-key
      - fleetdm-tls-cert
      - fleetdm-tls-key
    volumes: 
      - fleet-logs:/var/log/osquery
    networks: 
      - traefik_traefik-net
      - fleet-backend
    depends_on:
      - mysql
      - redis
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          #cpus: '2'
          memory: 100M
        reservations:
          #cpus: '0.5'
          memory: 50M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 120s
  
  ############################################## MySQL ##############################################
  mysql:
    image: mysql:8.0
    configs:
      - source: mysql-fleetdm-config
        target: /etc/mysql/conf.d/fleetdm.cnf
    environment: 
      MYSQL_ROOT_PASSWORD_FILE: "/run/secrets/mysql-root-password"
      MYSQL_PASSWORD_FILE: "/run/secrets/mysql-fleetdm-password"
      MYSQL_DATABASE: "fleet"
      MYSQL_USER: "fleet"
    secrets:
      - mysql-root-password
      - mysql-fleetdm-password
    volumes: 
      - fleet-db:/var/lib/mysql
    networks: 
      - fleet-backend
    deploy:
      resources:
        limits:
          #cpus: '2'
          memory: 1G
        reservations:
          #cpus: '1'
          memory: '300M'
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s


  ############################################## Redis ##############################################
  redis:
    image: redis:6.0.9-alpine
    networks: 
      - fleet-backend
    deploy:
      resources:
        limits:
          #cpus: '0.5'
          memory: 100M
        reservations:
          #cpus: '0.5'
          memory: 50M
      restart_policy:
        condition: on-failure

volumes:
  fleet-db:
  fleet-logs:

networks:
  fleet-backend:
  traefik_traefik-net:
    external: true

configs:
  nginx-config:
    file: ./conf/docker/nginx/nginx.conf
  nginx-fleetdm-config:
    file: ./conf/docker/nginx/fleetdm-swarm.conf
  mysql-fleetdm-config:
    file: ./conf/docker/mysql/fleetdm.cnf
  fleetdm-config:
    file: ./conf/docker/fleetdm/fleetdm-swarm-traefik.yml

secrets:
  mysql-root-password:
    external: true
  mysql-fleetdm-password:
    external: true
  fleetdm-tls-cert:
    file: conf/tls/fleet.crt
  fleetdm-tls-key:
    file: conf/tls/fleet.key
  fleetdm-jwt-key:
    external: true
