mysql:
  address: mysql:3306
  database: fleet
  username: fleet
  password_path: /run/secrets/mysql-fleetdm-password
redis:
  address: redis:6379
server:
  address: 0.0.0.0:8080
  tls: false
auth:
  jwt_key_path: /run/secrets/fleetdm-jwt-key
filesystem:
  #status_log_file: /var/log/osquery/status.log
  #result_log_file: /var/log/osquery/result.log
  status_log_file: /tmp/osquery/status.log
  result_log_file: /tmp/osquery/result.log
  enable_log_rotation: true
logging:
  json: true