ARG FLEETDM_VERSION 
FROM fleetdm/fleet:${FLEETDM_VERSION}

ARG FLEETDM_MYSQL_USER
ARG FLEETDM_MYSQL_PASSWORD
ARG FLEETDM_MYSQL_DATABASE
ARG FLEETDM_JWT_KEY

# Copy fleet config
USER root
RUN mkdir /etc/fleet
COPY conf/docker/fleetdm/fleetdm.yml /etc/fleet/fleet.yml
RUN sed -i "s/fleet_db_username/${FLEETDM_MYSQL_USER}/g" /etc/fleet/fleet.yml
RUN sed -i "s/fleet_db_password/${FLEETDM_MYSQL_PASSWORD}/g" /etc/fleet/fleet.yml
RUN sed -i "s/fleet_db_name/${FLEETDM_MYSQL_DATABASE}/g" /etc/fleet/fleet.yml
RUN sed -i "s/fleetdm_jwt_key/${FLEETDM_JWT_KEY}/g" /etc/fleet/fleet.yml


### Setup logging directory ###
RUN mkdir /var/log/osquery && \
	chown root:root /var/log/osquery && \
	touch /var/log/osquery/status.log && \
	touch /var/log/osquery/result.log && \
	chown fleet:fleet /var/log/osquery/result.log && \
	chown fleet:fleet /var/log/osquery/status.log

EXPOSE 8080
USER fleet
CMD ["fleet", "serve", "--config", "/etc/fleet/fleet.yml"]
