####################################################################
# Install/Setup Nginx
####################################################################
- name: Install/Setup Nginx
  apt:
    name: ['nginx']
    state: latest

- name: Copy nginx.conf
  template:
    src: conf/ansible/nginx/nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0400

- name: Copy nginx_fleetdm.conf
  template:
    src: 'conf/ansible/nginx/nginx_fleetdm.conf'
    dest: '/etc/nginx/conf.d/fleetdm.conf'
    owner: root
    group: root
    mode: 0400

- name: Start Nginx service
  service:
    name: nginx
    state: restarted
    enabled: yes

- name: NGINX healthcheck
  uri:
    url: "https://{{ ansible_default_ipv4.address }}:443"
    follow_redirects: none
    method: GET
    validate_certs: 'no'
  register: _result
  until: _result.status == 200
  retries: 720 # 720 * 5 seconds = 1hour (60*60/5)
  delay: 5 # Every 5 seconds
